[2023-01-01T00:00:16.399+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.user.extract scheduled__2022-12-31T00:00:00+00:00 [queued]>
[2023-01-01T00:00:16.467+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.user.extract scheduled__2022-12-31T00:00:00+00:00 [queued]>
[2023-01-01T00:00:16.469+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T00:00:16.470+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-01T00:00:16.472+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-01T00:00:16.567+0000] {taskinstance.py:1383} INFO - Executing <Task(ExtractOperator): user.extract> on 2022-12-31 00:00:00+00:00
[2023-01-01T00:00:16.589+0000] {standard_task_runner.py:55} INFO - Started process 515 to run task
[2023-01-01T00:00:16.610+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'user.extract', 'scheduled__2022-12-31T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpv0g_89e3']
[2023-01-01T00:00:16.614+0000] {standard_task_runner.py:83} INFO - Job 83: Subtask user.extract
[2023-01-01T00:00:16.679+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:545: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2023-01-01T00:00:17.015+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.user.extract scheduled__2022-12-31T00:00:00+00:00 [running]> on host 6bd76effbc07
[2023-01-01T00:00:17.505+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=user.extract
AIRFLOW_CTX_EXECUTION_DATE=2022-12-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-31T00:00:00+00:00
[2023-01-01T00:00:17.508+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/utilties/extract_operator.py", line 15, in execute
    {"first_created":{"$gte":self.filter['start'],"$lt":self.filter['end']}}
TypeError: must be str, not dict
[2023-01-01T00:00:17.567+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=dpt_cosmetic, task_id=user.extract, execution_date=20221231T000000, start_date=20230101T000016, end_date=20230101T000017
[2023-01-01T00:00:17.625+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 83 for task user.extract (must be str, not dict; 515)
[2023-01-01T00:00:17.681+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-01T00:00:17.810+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
