[2023-01-07T05:09:07.558+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bq_process.view_stats.execute_query manual__2023-01-07T05:08:48.661881+00:00 [queued]>
[2023-01-07T05:09:07.627+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: bq_process.view_stats.execute_query manual__2023-01-07T05:08:48.661881+00:00 [queued]>
[2023-01-07T05:09:07.629+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:09:07.631+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-07T05:09:07.632+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-07T05:09:07.729+0000] {taskinstance.py:1383} INFO - Executing <Task(BigQueryInsertJobOperator): view_stats.execute_query> on 2023-01-07 05:08:48.661881+00:00
[2023-01-07T05:09:07.751+0000] {standard_task_runner.py:55} INFO - Started process 338 to run task
[2023-01-07T05:09:07.776+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'bq_process', 'view_stats.execute_query', 'manual__2023-01-07T05:08:48.661881+00:00', '--job-id', '541', '--raw', '--subdir', 'DAGS_FOLDER/bigquery_dag.py', '--cfg-path', '/tmp/tmp92x__y3d']
[2023-01-07T05:09:07.788+0000] {standard_task_runner.py:83} INFO - Job 541: Subtask view_stats.execute_query
[2023-01-07T05:09:08.142+0000] {task_command.py:376} INFO - Running <TaskInstance: bq_process.view_stats.execute_query manual__2023-01-07T05:08:48.661881+00:00 [running]> on host fdf4acf1d8ed
[2023-01-07T05:09:08.547+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=bq_process
AIRFLOW_CTX_TASK_ID=view_stats.execute_query
AIRFLOW_CTX_EXECUTION_DATE=2023-01-07T05:08:48.661881+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-07T05:08:48.661881+00:00
[2023-01-07T05:09:08.553+0000] {connection.py:429} ERROR - Unable to retrieve connection from secrets backend (EnvironmentVariablesBackend). Checking subsequent secrets backend.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 422, in get_connection_from_secrets
    conn = secrets_backend.get_connection(conn_id=conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 115, in get_connection
    return self.deserialize_connection(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/secrets/base_secrets.py", line 67, in deserialize_connection
    return Connection.from_json(conn_id=conn_id, value=value)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 449, in from_json
    return Connection(conn_id=conn_id, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key_path'
[2023-01-07T05:09:08.592+0000] {base.py:71} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-01-07T05:09:08.597+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:204: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-01-07T05:09:08.632+0000] {bigquery.py:1554} INFO - Inserting job ***_bq_process_view_stats_execute_query_2023_01_07T05_08_48_661881_00_00_ef98478c7d8350032b57e568a6184056
[2023-01-07T05:09:09.416+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2153, in execute
    job = self._submit_job(hook, job_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2119, in _submit_job
    retry=self.result_retry,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/common/hooks/base_google.py", line 439, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 1560, in insert_job
    job.result(timeout=timeout, retry=retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Syntax error: Expected end of input but got identifier "count" at [3:13]

Location: asia-northeast3
Job ID: airflow_bq_process_view_stats_execute_query_2023_01_07T05_08_48_661881_00_00_ef98478c7d8350032b57e568a6184056

[2023-01-07T05:09:09.457+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=bq_process, task_id=view_stats.execute_query, execution_date=20230107T050848, start_date=20230107T050907, end_date=20230107T050909
[2023-01-07T05:09:09.513+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 541 for task view_stats.execute_query (400 Syntax error: Expected end of input but got identifier "count" at [3:13]

Location: asia-northeast3
Job ID: airflow_bq_process_view_stats_execute_query_2023_01_07T05_08_48_661881_00_00_ef98478c7d8350032b57e568a6184056
; 338)
[2023-01-07T05:09:09.552+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2023-01-07T05:09:09.731+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
