[2023-01-02T16:37:27.857+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.transform manual__2023-01-02T16:37:08.413817+00:00 [queued]>
[2023-01-02T16:37:27.914+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dpt_cosmetic.transaction.transform manual__2023-01-02T16:37:08.413817+00:00 [queued]>
[2023-01-02T16:37:27.916+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T16:37:27.917+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-01-02T16:37:27.918+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-01-02T16:37:28.015+0000] {taskinstance.py:1383} INFO - Executing <Task(TransformOperator): transaction.transform> on 2023-01-02 16:37:08.413817+00:00
[2023-01-02T16:37:28.033+0000] {standard_task_runner.py:55} INFO - Started process 262 to run task
[2023-01-02T16:37:28.049+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dpt_cosmetic', 'transaction.transform', 'manual__2023-01-02T16:37:08.413817+00:00', '--job-id', '232', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpnlmcdcdt']
[2023-01-02T16:37:28.052+0000] {standard_task_runner.py:83} INFO - Job 232: Subtask transaction.transform
[2023-01-02T16:37:29.226+0000] {task_command.py:376} INFO - Running <TaskInstance: dpt_cosmetic.transaction.transform manual__2023-01-02T16:37:08.413817+00:00 [running]> on host 703acec1b71e
[2023-01-02T16:37:30.158+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dpt_cosmetic
AIRFLOW_CTX_TASK_ID=transaction.transform
AIRFLOW_CTX_EXECUTION_DATE=2023-01-02T16:37:08.413817+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-02T16:37:08.413817+00:00
[2023-01-02T16:37:38.803+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

[2023-01-02T16:37:42.655+0000] {operator.py:104} INFO - successfully save the file,transaction
[2023-01-02T16:37:42.746+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dpt_cosmetic, task_id=transaction.transform, execution_date=20230102T163708, start_date=20230102T163727, end_date=20230102T163742
[2023-01-02T16:37:42.941+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-01-02T16:37:43.576+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
